#Keystore For Release APK
RELEASE_STORE_FILE=keystore/app_keystore.jks
RELEASE_STORE_PASSWORD=Jigs@1611
RELEASE_KEY_ALIAS=key0
RELEASE_KEY_PASSWORD=Jigs@1611
#Keystore For Debug APK
DEBUG_STORE_FILE=keystore/debug.keystore
DEBUG_STORE_PASSWORD=android
DEBUG_KEY_ALIAS=androiddebugkey
DEBUG_KEY_PASSWORD=android